<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'Baseusers' => 'om/Baseusers.php',
  'Baseuserspeer' => 'om/Baseuserspeer.php',
  'Baseusersquery' => 'om/Baseusersquery.php',
  'users' => 'users.php',
  'usersTableMap' => 'map/usersTableMap.php',
  'userspeer' => 'userspeer.php',
  'usersquery' => 'usersquery.php',
);