<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /home/bryan/Downloads/propeligniter/application/build/data/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'propeligniter' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=propeligniter',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'propeligniter',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-propeligniter-conf.php');
return $conf;